### ISSUE TITLE
Icon(Data) doesn't work/display

### ISSUE THREAD

**Issue by tonyborchert** [skaran921/flutter_awesome_alert_box#2]
`CustomBgAlertBox(
                    context: context,
                    title: "Your height is:",
                    icon: Icons.height,
                    bgColor: secondColor,
                    buttonColor: firstColor,
                    buttonTextColor: secondColor,
                    messageTextColor: fifthColor,
                    titleTextColor: fifthColor
);`

The Icon is not displaying in the desired position.

**Comment by tonyborchert** [comment]
`[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64,
    locale de-DE)
    • Flutter version 1.23.0-18.1.pre at /Users/tonyborchert/Developer/flutter
    • Framework revision 198df796aa (9 days ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tonyborchert/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] Connected device (3 available)
    • iPhone 11 Pro Max (mobile) • F2E727A1-9ADB-4814-94BA-98EA1C11FDF2 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)
    • Web Server (web)           • web-server                           •
      web-javascript • Flutter Tools
    • Chrome (web)               • chrome                               •
      web-javascript • Google Chrome 86.0.4240.111
    ! Error: Tony‘s iPhone™ XS maxk is not connected. Xcode will continue when
      Tony‘s iPhone™ XS maxk is connected. (code -13)
    ! Error: iPhone is not connected. Xcode will continue when iPhone is
      connected. (code -13)
    ! Error: iPhone von Victor is not connected. Xcode will continue when iPhone
      von Victor is connected. (code -13)
`
Flutter doctor

**Comment by tonyborchert** [comment]
`
import "package:flutter/material.dart";
import "package:flutter_awesome_alert_box/flutter_awesome_alert_box.dart";

void main() {
  runApp(MaterialApp(home: MyApp()));
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
        floatingActionButton: FloatingActionButton(
          backgroundColor: Colors.red,
          onPressed: (){
            CustomBgAlertBox(
              context: context,
              icon: Icons.add_a_photo,
              bgColor: Colors.red,
              buttonTextColor: Colors.yellow,


            );

          },

        ),
        body: Container(
          color: Colors.yellow,
        ),
      );

  }
}
`

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-10-24 at 12 54 17](https://user-images.githubusercontent.com/65500763/97079931-0848e600-15f8-11eb-8196-ea43bccd9033.png)

**Comment by tonyborchert** [comment]
Pull request #3: Is a fix

**Comment by skaran921** [comment]
@bit-burger  thanks for your contribution. i have merge your pull request.
